[Main]
font=cascadia code
fontsize=12
lastfile=yes
backup=no
tabsz=4
nospaces=yes
terminal=xfce4-terminal
filemgr=thunar
appath=/home/ml/apps/python/projects/TKedit/tkedit.pyc
autoindent=yes
md2html=yes
debounce=100
theme=cyborg
style=material


#| Style Name | Description |
#|------------|-------------|
#| DARK ||
#| `material` | Based on Material Design |
#| `dracula` | Purple/pink tones popular vampire-themed |
#| `zenburn` | Low-contrast easy on the eyes |
#| `monokai` | Classic dark theme from Sublime Text |
#| `default` | Good |
#| `paraiso-dark` | Paraiso Dark editor-style |
#| `solarized-dark` | Popular low-contrast dark theme |
#| `native` | Pygments own dark theme |
#| `gruvbox-dark` | Retro groove warm colors |
#| LIGHT ||
#| `default` | Good |
#| `borland` | classic light/bright editor look |
#| `bw` | black/white / high readability |
#| `tango` | lighter Tango palette  |
#| `pastie` | often used as a light-ish palette |
#
# ------- themes --------
# darkly cyborg superhero solar
# LIGHT
# sandstone yeti pulse cosmo flatly litera minty
# lumen journal simplex cerculean
#
# favorite themes DARK:
#    solar / paraiso-dark
#    cyborg / material
#    darkly / gruvbox-dark
#    superhero / monokai
#    darkly / zenburn
# Light:
#    lumen or cosmo / borland or tango
